spring.application.name=biomas
spring.datasource.url = jdbc:postgresql://localhost:5432/biomes
spring.datasource.username = postgres
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto = update
spring.graphql.graphiql.enabled=true
